FROM openjdk:21-slim AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 ./mvnw -f $HOME/pom.xml clean package -Dskiptests

FROM openjdk:21-slim
ARG JAR_FILE=/usr/app/target/*.jar
ARG SERVER_PORT
COPY --from=build $JAR_FILE /app/runner.jar
EXPOSE $SERVER_PORT
ENTRYPOINT java -jar /app/runner.jar