FROM maven:latest AS builder
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:21-slim
COPY --from=builder /home/app/target/awardrobe-0.0.1-SNAPSHOT.jar /usr/local/lib/awardrobe.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java","-jar","/usr/local/lib/awardrobe.jar"]