FROM openjdk:21-slim AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

FROM openjdk:21-slim
ARG JAR_FILE=/usr/app/target/*.jar
ARG SERVER_PORT
COPY --from=build $JAR_FILE /app/runner.jar
EXPOSE $SERVER_PORT
ENTRYPOINT java -jar /app/runner.jar